version: '3.8'
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hkt_database
      - MYSQL_ROOT_PASSWORD=hkt_db_2022
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - db
    environment:
      NODE_ENV: base
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: hkt_db_2022
      DB_NAME: hkt_database
    links:
      - db
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '8000'
    ports:
      - '8000:8000'
    command: npm run dev
volumes:
  db:
    driver: local
